### ISSUE TITLE
Exception has occurred: RangeError [ERR_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by Jason3S** [gitkraken/vscode-gitlens#1699]
- GitLens Version:
   GitLens (Insiders) v2021.10.2305
- Git Version: Run `git --version`
   git version 2.26.0

- VSCode Version: Run `code --version`
  Version: 1.61.2
  Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
  Date: 2021-10-19T15:49:28.381Z
  Electron: 13.5.1
  Chrome: 91.0.4472.164
  Node.js: 14.16.0
  V8: 9.1.269.39-electron.0
  OS: Darwin x64 20.6.0
- OS Version:
  OS: Darwin x64 20.6.0

Steps to Reproduce:

I don't have good step. I was debugging my extension and this error showed up.

![image](https://user-images.githubusercontent.com/3740137/138838715-3f5fe331-4d4e-44f5-ab2b-e9d2a2b14eed.png)

<details>
<summary>Call Stack: Exception has occurred: RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 1</summary>

```
Exception has occurred: RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 1
  at Object.getSystemErrorName (util.js:231:11)
    at errnoException (internal/errors.js:501:21)
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at spawn (child_process.js:562:9)
    at execFile (child_process.js:246:17)
    at electron/js2c/asar_bundle.js:5:2242
    at /Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.10.2305/dist/webpack:/gitlens-insiders/src/git/shell.ts:183:16
    at new Promise (<anonymous>)
    at run (/Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.10.2305/dist/webpack:/gitlens-insiders/src/git/shell.ts:182:9)
    at git (/Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.10.2305/dist/webpack:/gitlens-insiders/src/git/git.ts:134:13)
    at Object.rev_parse__show_toplevel (/Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.10.2305/dist/webpack:/gitlens-insiders/src/git/git.ts:1298:23)
    at Object.getRepoPathCore (/Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.10.2305/dist/webpack:/gitlens-insiders/src/git/gitService.ts:3435:21)
    at Object.<anonymous> (/Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.10.2305/dist/webpack:/gitlens-insiders/src/system/decorators/log.ts:113:16)
    at Object.getRepoPath (/Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.10.2305/dist/webpack:/gitlens-insiders/src/git/gitService.ts:3381:25)
    at Function.fromUri (/Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.10.2305/dist/webpack:/gitlens-insiders/src/git/gitUri.ts:324:26)
    at R.initialize (/Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.10.2305/dist/webpack:/gitlens-insiders/src/trackers/trackedDocument.ts:74:15)
    at Function.create (/Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.10.2305/dist/webpack:/gitlens-insiders/src/trackers/trackedDocument.ts:30:3)
    at Object.getLogForFile (/Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.10.2305/dist/webpack:/gitlens-insiders/src/git/gitService.ts:2316:15)
    at Object.getCommitForFile (/Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.10.2305/dist/webpack:/gitlens-insiders/src/git/gitService.ts:1517:15)
    at zi.provideDetailsHover (/Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.10.2305/dist/webpack:/gitlens-insiders/src/hovers/lineHoverController.ts:115:16)
    at s.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
```
</details>

**Comment by eamodio** [comment]
Wow -- that's an odd one. It looks like `child_process` `spawn` returned some bogus error code or something. Without reproducible steps I don't see anything I can fix here -- since this is inside node.js itself. Have you seen it more than this one time?

**Comment by Jason3S** [comment]
I have no idea why Node was having an issue. But it prevented me from debugging, so I had to uninstall the extension.

https://github.com/Axosoft/vscode-gitlens/blob/28a3a6bb627529d294f866d52ef65292281e2979/src/hovers/lineHoverController.ts#L115-L117

But it is possible to catch the issue: `.catch(() => null)`

```ts
			logCommit = await Container.git.getCommitForFile(commit.repoPath, commit.uri.fsPath, {
				ref: commit.sha,
			}).catch(() => null);
```

**Comment by fai814** [comment]
github-actions[bot] ***@***.***> 於 2021年11月12日週五 下午1:01寫道：
