### ISSUE TITLE
Error loading webview: Error: Could not register service workers: InvalidStateError

### ISSUE THREAD

**Issue by ctsstc** [gitkraken/vscode-gitlens#2497]
### Description

I started getting this error when I tried to do an interactive rebase, I tried restarting VSCode, uninstalling and reinstalling the extension, fully restarting VSCode again by closing it first, but no luck.

When I uninstall the extension the error does not appear on restarting VSCode, but when the extension is installed it  displays right after VSCode starts.

## Error

```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

### GitLens Version

13.2.0

### VS Code Version

Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z (23 hrs ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No

### Logs, Screenshots, Screen Captures, etc

Output -> Window has the following:

```
2023-02-09 12:47:23.979 [error] No provider registered for 'output:extension-output-eamodio.gitlens-%231-GitLens': Error: No provider registered for 'output:extension-output-eamodio.gitlens-%231-GitLens'
    at Ie.getProvider (/Users/coder/.vscode/extensions/eamodio.gitlens-13.2.0/dist/gitlens.js:14:18020)
    at Ie.findRepository (/Users/coder/.vscode/extensions/eamodio.gitlens-13.2.0/dist/gitlens.js:14:30426)
    at Ie.getOrOpenRepository (/Users/coder/.vscode/extensions/eamodio.gitlens-13.2.0/dist/gitlens.js:14:31078)
    at Ie.Q.<computed> (/Users/coder/.vscode/extensions/eamodio.gitlens-13.2.0/dist/gitlens.js:218:20049)
    at Ie.getOrOpenRepositoryForEditor (/Users/coder/.vscode/extensions/eamodio.gitlens-13.2.0/dist/gitlens.js:14:31238)
    at Ie.Q.<computed> (/Users/coder/.vscode/extensions/eamodio.gitlens-13.2.0/dist/gitlens.js:218:20049)
    at Wh.steps (/Users/coder/.vscode/extensions/eamodio.gitlens-13.2.0/dist/gitlens.js:45:419)
    at Wh.next (/Users/coder/.vscode/extensions/eamodio.gitlens-13.2.0/dist/gitlens.js:38:60347)
    at Et.getCommandStep (/Users/coder/.vscode/extensions/eamodio.gitlens-13.2.0/dist/gitlens.js:153:66389)
    at Et.showLoadingIfNeeded (/Users/coder/.vscode/extensions/eamodio.gitlens-13.2.0/dist/gitlens.js:153:65402)
    at Et.execute (/Users/coder/.vscode/extensions/eamodio.gitlens-13.2.0/dist/gitlens.js:153:64881)
```

Edit: I also tried the pre-release version and had the same error notification bubble pop up upon restarting VSCode.

**Comment by jkelroy** [comment]
Hello @ctsstc, does DianaNites suggestion resolves the issue for you? 

If it does not, can you provide more information regarding your steps to reproduce the issue? For example, can you reproduce the issue using the [GitLens repository](https://github.com/gitkraken/vscode-gitlens)? 

Also, can you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach all the log from the both _GitLens_ and _GitLens (Git)_ channels.

**Comment by ctsstc** [comment]
It has been gone for quite some time, I think I ended up with a new machine.
