### ISSUE TITLE
Cannot read properties of undefined (reading 'start')

### ISSUE THREAD

**Issue by ulugbekna** [gitkraken/vscode-gitlens#2499]
### Description

With the latest update of gitlens (2023.2.1004), I get TypeError - `Cannot read properties of undefined (reading 'start')` constantly (disabling line blame fixes it) 

```
TypeError: Cannot read properties of undefined (reading 'start')
    at Function.getId (vscode-file://vscode-app/Users/ulugbekna/.vscode-insiders/extensions/eamodio.gitlens-2023.2.1004/dist/gitlens.js:1:370294)
    at da.get id [as id] (vscode-file://vscode-app/Users/ulugbekna/.vscode-insiders/extensions/eamodio.gitlens-2023.2.1004/dist/gitlens.js:1:370433)
    at LineHistoryView.getNodeLastKnownLimit (vscode-file://vscode-app/Users/ulugbekna/.vscode-insiders/extensions/eamodio.gitlens-2023.2.1004/dist/gitlens.js:1:336968)
    at da.<instance_members_initializer> (vscode-file://vscode-app/Users/ulugbekna/.vscode-insiders/extensions/eamodio.gitlens-2023.2.1004/dist/gitlens.js:1:374212)
    at new da (vscode-file://vscode-app/Users/ulugbekna/.vscode-insiders/extensions/eamodio.gitlens-2023.2.1004/dist/gitlens.js:1:370139)
    at LineHistoryTrackerNode.getChildren (vscode-file://vscode-app/Users/ulugbekna/.vscode-insiders/extensions/eamodio.gitlens-2023.2.1004/dist/gitlens.js:1:375997)
    at b.R (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:18944)
    at b.getChildren (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:15363)
c @ notificationsAlerts.ts:40
```

This occurs with vscode repo open. 

### GitLens Version

2023.2.1004

### VS Code Version

Version: 1.76.0-insider (Universal)
Commit: 853b32bad26ed5ffe2d29b95be45adc7f753e35a
Date: 2023-02-09T05:23:48.935Z (1 day ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

### Git Version

git version 2.37.1 (Apple Git-137.1)

**Comment by eamodio** [comment]
Fixed by https://github.com/gitkraken/vscode-gitlens/commit/8a503a35d8340e3067261e95f570de0cbbfb5fd1

**Comment by eamodio** [comment]
Sorry for the issues, and thanks for the report! I've kicked off a new pre-release build so this should be out shortly.
