### ISSUE TITLE
'e.replace is not a function' Error in New Version(14.9.0)

### ISSUE THREAD

**Issue by sanghyun-qesg** [gitkraken/vscode-gitlens#3181]
### Description

After updating GitLens, I noticed that the line blame feature wasn't functioning properly. Additionally, when clicking on branches within the extension, while some showed no issues, others failed to expand and resulted in an error where no related commits were displayed.

I was able to check logs via the Extension Host and have currently resolved the issue by downgrading GitLens to an earlier version.

### GitLens Version

14.9.0

### VS Code Version

Version: 1.87.1 (user setup)
Commit: 1e790d77f81672c49be070e04474901747115651
Date: 2024-03-06T00:21:36.258Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

### Git Version

git version 2.36.1.windows.1

### Logs, Screenshots, Screen Captures, etc

```cmd
2024-03-08 11:24:13.807 [error] TypeError: e.replace is not a function
	at String.replaceAll (c:\****\****\.vscode\extensions\ms-python.python-2022.8.0\out\client\extension.js:2:148792)
	at m (c:\****\****\.vscode\extensions\eamodio.gitlens-14.9.0\dist\gitlens.js:1083:7445)
	at U (c:\****\****\.vscode\extensions\eamodio.gitlens-14.9.0\dist\gitlens.js:1083:10274)
	at CommitFormatter._padOrTruncate (c:\****\****\.vscode\extensions\eamodio.gitlens-14.9.0\dist\gitlens.js:1054:3641)
	at get message [as message] (c:\****\****\.vscode\extensions\eamodio.gitlens-14.9.0\dist\gitlens.js:1049:236)
	at q (c:\****\****\.vscode\extensions\eamodio.gitlens-14.9.0\dist\gitlens.js:1083:11709)
	at CommitFormatter.fromTemplateCore (c:\****\****\.vscode\extensions\eamodio.gitlens-14.9.0\dist\gitlens.js:1054:4313)
	at CommitFormatter.fromTemplate (c:\****\****\.vscode\extensions\eamodio.gitlens-14.9.0\dist\gitlens.js:1054:2383)
	at C (c:\****\****\.vscode\extensions\eamodio.gitlens-14.9.0\dist\gitlens.js:650:23871)
	at p (c:\****\****\.vscode\extensions\eamodio.gitlens-14.9.0\dist\gitlens.js:750:5251)
	at LineAnnotationController.refresh (c:\****\****\.vscode\extensions\eamodio.gitlens-14.9.0\dist\gitlens.js:750:6233)
```

**Comment by d13** [comment]
I was able to reproduce the issue after installing the Python extension at version 2022.8.0, which appears to have been fixed with https://github.com/microsoft/vscode-python/pull/20626 and released with https://github.com/microsoft/vscode-python/releases/tag/2023.4.0. Please update your Python extension and you should be all set.
