### ISSUE TITLE
Gitlens not usable with bat/cmd wrappers of Git

### ISSUE THREAD

**Issue by dpnub** [gitkraken/vscode-gitlens#580]
- GitLens Version: 9.0.3
- VSCode Version: 1.29.1
- OS Version: Windows 10 x64

I have problem with Gitlens 9.x in binding with Cygwin git under Windows.
I run git from some bat-wrapper, since I need to translate the paths between Windows and Cygwin.
As far as I can see in the logs, Gitlens cannot execute the git-wrapper specified in the "git.path" setting. For this reason, no function of the Gitlens is available.

I got a messages: "An unknown error occurred. Please consult the log for more details."

And this error message in debug console:
/C:/develop/VSCode/resources/app/out/vs/workbench/workbench.main.js:2429 Error
	at Object (D:\home\dap\.vscode\extensions\eamodio.gitlens-9.0.3\dist\extension.js:1:269559)
	at exithandler (child_process.js:294:5)
	at ChildProcess.errorhandler (child_process.js:306:5)
	at emitOne (events.js:116:13)
	at ChildProcess.emit (events.js:211:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
t.onDidNotificationChange @ /C:/develop/VSCode/resources/app/out/vs/workbench/workbench.main.js:2429

As I understand it, this is due to this specific of Nodejs: 
https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows

Elsewhere, VSCode use a different method to execute git. So the rest of the functions work without problems.

Steps to Reproduce:

1. Install some bat-wrapper. Now I use this: https://gist.github.com/dantmnf/bca20b670ce6b14bf9c16d630c355ed7

2. Specify path to wrapper in "git.path" setting.

3. Reload VSCode

4. Open any Gitlens window.

**Comment by mplwork** [comment]
I have the same problem but can't find those logs I am supposed to consult. Where are they? I saw them once by accident. And I'd really like to see this bug fixed.

**Comment by eamodio** [comment]
You can get output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. 

Any help you can offer here would be greatly appreciated.

**Comment by dpnub** [comment]
Му logs

Gitlens log:
```
[2019-03-11 12:31:22:902] [1] GitService.initialize
[2019-03-11 12:31:23:759] Git found: 2.17.0 @ C:\bin\far\gitwrapper.cmd • 330 ms
[2019-03-11 12:31:23:759] [1] GitService.initialize completed • 856 ms
[2019-03-11 12:31:23:760] Starting repository search in 1 folders
[2019-03-11 12:31:23:760] Searching for repositories (depth=1) in 'h:\work\office\profile-search' ...
[2019-03-11 12:31:23:825] GitLens(v9.5.1) activated • 954 ms
[2019-03-11 12:31:24:185] [2] GitUri.fromUri — e=Uri(file:///c:/Users/my_user/AppData/Roaming/Code/User/settings.json)
[2019-03-11 12:31:24:185] [3] GitService.getRepoPath — e=Uri(file:///c:/Users/my_user/AppData/Roaming/Code/User/settings.json)
[2019-03-11 12:31:24:186] [4] GitService.getRepository — e=Uri(file:///c:/Users/my_user/AppData/Roaming/Code/User/settings.json), t={"skipCacheUpdate":true}
[2019-03-11 12:31:24:256] [h:\work\office\profile-search] git rev-parse --show-toplevel • 495 ms 
[2019-03-11 12:31:24:264] Repository found in '/mnt/hdd/h/work/office/profile-search'
[2019-03-11 12:31:24:735] [h:\work\office\profile-search] git rev-parse --show-toplevel • 460 ms 
[2019-03-11 12:31:24:735] Repository found in '/mnt/hdd/h/work/office/profile-search'
[2019-03-11 12:31:24:736] Completed repository search (depth=1) in 'h:\work\office\profile-search' • 976 ms
[2019-03-11 12:31:24:740] git — -c, core.quotepath=false, -c, color.ui=false, remote, -v,   cwd='/mnt/hdd/h/work/office/profile-search'

  
Error
[2019-03-11 12:31:24:741] [/mnt/hdd/h/work/office/profile-search] git remote -v • 3 ms 
[2019-03-11 12:31:24:745] module.exports.Ye.Object
Error
[2019-03-11 12:31:24:747] [4] GitService.getRepository returned undefined • 560 ms
[2019-03-11 12:31:25:059] [c:\Users\my_user\AppData\Roaming\Code\User] git rev-parse --show-toplevel • 312 ms 
[2019-03-11 12:31:25:059] [3] GitService.getRepoPath returned undefined • 874 ms
[2019-03-11 12:31:25:060] [2] GitUri.fromUri returned GitUri(file:///c:/Users/my_user/AppData/Roaming/Code/User/settings.json) • 874 ms
[2019-03-11 12:31:25:060] [5] GitService.getRepository — e=GitUri(file:///c:/Users/my_user/AppData/Roaming/Code/User/settings.json)
[2019-03-11 12:31:25:060] [5] GitService.getRepository returned undefined • 0 ms
[2019-03-11 12:31:25:410] [] git ls-files -- c:\Users\my_user\AppData\Roaming\Code\User\settings.json • 349 ms 
[2019-03-11 12:31:25:410] [6] GitService.isTracked returned false • 349 ms — e=GitUri(file:///c:/Users/my_user/AppData/Roaming/Code/User/settings.json)
[2019-03-11 12:31:45:128] [7] GitService.getOrderedRepositories
[2019-03-11 12:31:45:128] [8] GitService.getRepositories
[2019-03-11 12:31:45:129] [8] GitService.getRepositories completed • 0 ms
[2019-03-11 12:31:45:129] [7] GitService.getOrderedRepositories completed • 0 ms
[2019-03-11 12:31:45:129] [9] GitService.getStatusForRepo — e=/mnt/hdd/h/work/office/profile-search
[2019-03-11 12:31:45:132] git — -c, core.quotepath=false, -c, color.ui=false, -c, color.status=false, status, --porcelain=v2, --branch, -u,   cwd='/mnt/hdd/h/work/office/profile-search'

  
Error
[2019-03-11 12:31:45:132] [/mnt/hdd/h/work/office/profile-search] git status --porcelain=v2 --branch -u • 2 ms 
[2019-03-11 12:31:45:132] [9] GitService.getStatusForRepo — failed • 3 ms
Error
[2019-03-11 12:31:45:379] [a] RepositoriesNode(0).onVisibilityChanged — e={"visible":true}
[2019-03-11 12:31:45:379] [b] RepositoriesNode(0).ensureSubscription
[2019-03-11 12:31:45:379] [c] RepositoriesNode(0).subscribe
[2019-03-11 12:31:45:380] [d] RepositoriesNode(0).triggerChange
[2019-03-11 12:31:45:380] [e] RepositoriesView.refreshNode — e=RepositoriesNode
[2019-03-11 12:31:45:380] [f] RepositoriesNode(0).refresh — false
[2019-03-11 12:31:45:380] [10] GitService.getOrderedRepositories
[2019-03-11 12:31:45:380] [11] GitService.getRepositories
[2019-03-11 12:31:45:380] [a] RepositoriesNode(0).onVisibilityChanged completed • 1 ms
[2019-03-11 12:31:45:380] [12] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).onVisibilityChanged — e={"visible":true}
[2019-03-11 12:31:45:380] [13] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription
[2019-03-11 12:31:45:381] [14] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).subscribe
[2019-03-11 12:31:45:381] [15] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).triggerChange
[2019-03-11 12:31:45:381] [16] RepositoriesView.refreshNode — e=RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search))
[2019-03-11 12:31:45:381] [17] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).refresh — false
[2019-03-11 12:31:45:381] [18] GitService.getStatusForRepo — e=/mnt/hdd/h/work/office/profile-search
[2019-03-11 12:31:45:383] [19] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription
[2019-03-11 12:31:45:384] [12] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).onVisibilityChanged completed • 3 ms
[2019-03-11 12:31:45:384] [c] RepositoriesNode(0).subscribe completed • 4 ms
[2019-03-11 12:31:45:384] [14] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).subscribe completed • 3 ms
[2019-03-11 12:31:45:384] [19] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription completed • 0 ms
[2019-03-11 12:31:45:384] [b] RepositoriesNode(0).ensureSubscription completed • 4 ms
[2019-03-11 12:31:45:384] [11] GitService.getRepositories completed • 3 ms
[2019-03-11 12:31:45:384] [13] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription completed • 3 ms
[2019-03-11 12:31:45:384] [17] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).refresh completed • 2 ms
[2019-03-11 12:31:45:384] [10] GitService.getOrderedRepositories completed • 3 ms
[2019-03-11 12:31:45:384] [1a] RepositoriesView.triggerNodeChange — e=RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search))
[2019-03-11 12:31:45:384] [1a] RepositoriesView.triggerNodeChange completed • 0 ms
[2019-03-11 12:31:45:384] [1b] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).refresh
[2019-03-11 12:31:45:384] [1c] GitService.getStatusForRepo — e=/mnt/hdd/h/work/office/profile-search
[2019-03-11 12:31:45:385] [1d] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription
[2019-03-11 12:31:45:385] [1e] RepositoriesNode(0).ensureSubscription
[2019-03-11 12:31:45:386] [16] RepositoriesView.refreshNode completed • 4 ms
[2019-03-11 12:31:45:386] [15] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).triggerChange completed • 4 ms
[2019-03-11 12:31:45:386] [1d] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription completed • 0 ms
[2019-03-11 12:31:45:386] [1e] RepositoriesNode(0).ensureSubscription completed • 0 ms
[2019-03-11 12:31:45:386] [f] RepositoriesNode(0).refresh completed • 5 ms
[2019-03-11 12:31:45:386] [1f] RepositoriesView.triggerNodeChange — e=RepositoriesNode
[2019-03-11 12:31:45:386] [1f] RepositoriesView.triggerNodeChange completed • 0 ms
[2019-03-11 12:31:45:386] [1b] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).refresh completed • 1 ms
[2019-03-11 12:31:45:386] [e] RepositoriesView.refreshNode completed • 6 ms
[2019-03-11 12:31:45:386] [d] RepositoriesNode(0).triggerChange completed • 6 ms
[2019-03-11 12:31:45:387] git — -c, core.quotepath=false, -c, color.ui=false, -c, color.status=false, status, --porcelain=v2, --branch, -u,   cwd='/mnt/hdd/h/work/office/profile-search'

  
Error
[2019-03-11 12:31:45:387] [/mnt/hdd/h/work/office/profile-search] git status --porcelain=v2 --branch -u • 5 ms 
[2019-03-11 12:31:45:387] git — status, --porcelain=v2, --branch, -u,   cwd='/mnt/hdd/h/work/office/profile-search'

  
Error
[2019-03-11 12:31:45:387] [/mnt/hdd/h/work/office/profile-search] git status --porcelain=v2 --branch -u • 2 ms (await) 
[2019-03-11 12:31:45:387] [18] GitService.getStatusForRepo — failed • 5 ms
Error
[2019-03-11 12:31:45:387] [1c] GitService.getStatusForRepo — failed • 2 ms
Error
[2019-03-11 12:31:55:297] [20] RepositoriesNode(0).onVisibilityChanged — e={"visible":false}
[2019-03-11 12:31:55:297] [21] RepositoriesNode(0).ensureSubscription
[2019-03-11 12:31:55:297] [22] RepositoriesNode(0).unsubscribe
[2019-03-11 12:31:55:297] [20] RepositoriesNode(0).onVisibilityChanged completed • 0 ms
[2019-03-11 12:31:55:297] [23] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).onVisibilityChanged — e={"visible":false}
[2019-03-11 12:31:55:297] [24] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription
[2019-03-11 12:31:55:297] [25] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).unsubscribe
[2019-03-11 12:31:55:297] [23] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).onVisibilityChanged completed • 0 ms
[2019-03-11 12:31:55:297] [22] RepositoriesNode(0).unsubscribe completed • 0 ms
[2019-03-11 12:31:55:297] [25] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).unsubscribe completed • 0 ms
[2019-03-11 12:31:55:297] [21] RepositoriesNode(0).ensureSubscription completed • 0 ms
[2019-03-11 12:31:55:298] [24] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription completed • 0 ms
[2019-03-11 12:31:57:146] [26] RepositoriesNode(0).onVisibilityChanged — e={"visible":true}
[2019-03-11 12:31:57:146] [27] RepositoriesNode(0).ensureSubscription
[2019-03-11 12:31:57:146] [28] RepositoriesNode(0).subscribe
[2019-03-11 12:31:57:146] [29] RepositoriesNode(0).triggerChange
[2019-03-11 12:31:57:146] [2a] RepositoriesView.refreshNode — e=RepositoriesNode
[2019-03-11 12:31:57:146] [2b] RepositoriesNode(0).refresh — false
[2019-03-11 12:31:57:147] [2c] GitService.getOrderedRepositories
[2019-03-11 12:31:57:147] [2d] GitService.getRepositories
[2019-03-11 12:31:57:147] [26] RepositoriesNode(0).onVisibilityChanged completed • 1 ms
[2019-03-11 12:31:57:147] [2e] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).onVisibilityChanged — e={"visible":true}
[2019-03-11 12:31:57:147] [2f] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription
[2019-03-11 12:31:57:147] [30] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).subscribe
[2019-03-11 12:31:57:147] [31] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).triggerChange
[2019-03-11 12:31:57:148] [32] RepositoriesView.refreshNode — e=RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search))
[2019-03-11 12:31:57:148] [33] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).refresh — false
[2019-03-11 12:31:57:148] [34] GitService.getStatusForRepo — e=/mnt/hdd/h/work/office/profile-search
[2019-03-11 12:31:57:150] [35] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription
[2019-03-11 12:31:57:150] [2e] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).onVisibilityChanged completed • 3 ms
[2019-03-11 12:31:57:150] [28] RepositoriesNode(0).subscribe completed • 4 ms
[2019-03-11 12:31:57:150] [30] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).subscribe completed • 3 ms
[2019-03-11 12:31:57:150] [35] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription completed • 0 ms
[2019-03-11 12:31:57:150] [27] RepositoriesNode(0).ensureSubscription completed • 4 ms
[2019-03-11 12:31:57:150] [2d] GitService.getRepositories completed • 3 ms
[2019-03-11 12:31:57:150] [2f] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription completed • 3 ms
[2019-03-11 12:31:57:150] [33] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).refresh completed • 2 ms
[2019-03-11 12:31:57:151] [2c] GitService.getOrderedRepositories completed • 4 ms
[2019-03-11 12:31:57:151] [36] RepositoriesView.triggerNodeChange — e=RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search))
[2019-03-11 12:31:57:151] [36] RepositoriesView.triggerNodeChange completed • 0 ms
[2019-03-11 12:31:57:151] [37] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).refresh
[2019-03-11 12:31:57:151] [38] GitService.getStatusForRepo — e=/mnt/hdd/h/work/office/profile-search
[2019-03-11 12:31:57:152] [39] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription
[2019-03-11 12:31:57:152] [3a] RepositoriesNode(0).ensureSubscription
[2019-03-11 12:31:57:152] [32] RepositoriesView.refreshNode completed • 4 ms
[2019-03-11 12:31:57:152] [31] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).triggerChange completed • 4 ms
[2019-03-11 12:31:57:152] [39] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).ensureSubscription completed • 0 ms
[2019-03-11 12:31:57:152] [3a] RepositoriesNode(0).ensureSubscription completed • 0 ms
[2019-03-11 12:31:57:152] [2b] RepositoriesNode(0).refresh completed • 5 ms
[2019-03-11 12:31:57:152] [3b] RepositoriesView.triggerNodeChange — e=RepositoriesNode
[2019-03-11 12:31:57:153] [3b] RepositoriesView.triggerNodeChange completed • 0 ms
[2019-03-11 12:31:57:153] [37] RepositoryNode(0:gitlens:repository(/mnt/hdd/h/work/office/profile-search)).refresh completed • 1 ms
[2019-03-11 12:31:57:153] [2a] RepositoriesView.refreshNode completed • 6 ms
[2019-03-11 12:31:57:153] [29] RepositoriesNode(0).triggerChange completed • 6 ms
[2019-03-11 12:31:57:153] git — -c, core.quotepath=false, -c, color.ui=false, -c, color.status=false, status, --porcelain=v2, --branch, -u,   cwd='/mnt/hdd/h/work/office/profile-search'

  
Error
[2019-03-11 12:31:57:153] [/mnt/hdd/h/work/office/profile-search] git status --porcelain=v2 --branch -u • 5 ms 
[2019-03-11 12:31:57:153] git — status, --porcelain=v2, --branch, -u,   cwd='/mnt/hdd/h/work/office/profile-search'

  
Error
[2019-03-11 12:31:57:153] [/mnt/hdd/h/work/office/profile-search] git status --porcelain=v2 --branch -u • 2 ms (await) 
[2019-03-11 12:31:57:154] [34] GitService.getStatusForRepo — failed • 5 ms
Error
[2019-03-11 12:31:57:154] [38] GitService.getStatusForRepo — failed • 2 ms
Error
[2019-03-11 12:32:23:336] [3c] RepositoriesNode(0).onActiveEditorChanged
[2019-03-11 12:32:23:336] [3c] RepositoriesNode(0).onActiveEditorChanged completed • 0 ms
[2019-03-11 12:32:28:334] [3d] RepositoriesNode(0).onActiveEditorChanged
[2019-03-11 12:32:28:335] [3d] RepositoriesNode(0).onActiveEditorChanged completed • 0 ms
[2019-03-11 12:34:55:348] [3e] RepositoriesNode(0).onActiveEditorChanged
[2019-03-11 12:34:55:348] [3e] RepositoriesNode(0).onActiveEditorChanged completed • 0 ms
[2019-03-11 12:34:59:242] [3f] RepositoriesNode(0).onActiveEditorChanged
[2019-03-11 12:34:59:242] [3f] RepositoriesNode(0).onActiveEditorChanged completed • 0 ms
[2019-03-11 12:35:03:019] [40] RepositoriesNode(0).onActiveEditorChanged
[2019-03-11 12:35:03:019] [40] RepositoriesNode(0).onActiveEditorChanged completed • 0 ms
[2019-03-11 12:36:21:277] [41] RepositoriesNode(0).onActiveEditorChanged
[2019-03-11 12:36:21:277] [41] RepositoriesNode(0).onActiveEditorChanged completed • 0 ms
```

Gitlens (Git) log:
```
[2019-03-11 12:31:24:264] [h:\work\office\profile-search] git rev-parse --show-toplevel • 495 ms 
[2019-03-11 12:31:24:735] [h:\work\office\profile-search] git rev-parse --show-toplevel • 460 ms 
[2019-03-11 12:31:24:741] [/mnt/hdd/h/work/office/profile-search] git remote -v • 3 ms 
[2019-03-11 12:31:25:059] [c:\Users\my_user\AppData\Roaming\Code\User] git rev-parse --show-toplevel • 312 ms 
[2019-03-11 12:31:25:410] [] git ls-files -- c:\Users\my_user\AppData\Roaming\Code\User\settings.json • 349 ms 
[2019-03-11 12:31:45:132] [/mnt/hdd/h/work/office/profile-search] git status --porcelain=v2 --branch -u • 2 ms 
[2019-03-11 12:31:45:387] [/mnt/hdd/h/work/office/profile-search] git status --porcelain=v2 --branch -u • 5 ms 
[2019-03-11 12:31:45:387] [/mnt/hdd/h/work/office/profile-search] git status --porcelain=v2 --branch -u • 2 ms (await) 
[2019-03-11 12:31:57:153] [/mnt/hdd/h/work/office/profile-search] git status --porcelain=v2 --branch -u • 5 ms 
[2019-03-11 12:31:57:153] [/mnt/hdd/h/work/office/profile-search] git status --porcelain=v2 --branch -u • 2 ms (await) 
```

Git log:
```
Looking for git in: C:\bin\far\gitwrapper.cmd
Using git 2.17.0 from C:\bin\far\gitwrapper.cmd
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: h:\work\office\profile-search
> git rev-parse --show-toplevel
> git status -z -u
> git check-ignore -z --stdin
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /mnt/hdd/c/Users/my_user/AppData/Roaming/Code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cygpath: can't convert empty path
```

**Comment by sunlho** [comment]
Hello, may I ask if there’s been any progress on this issue? I’m currently encountering a similar problem.

Specifically, GitLens is not working — the inline commit information is not showing

When I open the GitLens Inspect panel, I get the following error:

spawn C:\cygwin64\git\git.exe ENOENT

I’m using this wrapper: [https://github.com/nukata/cyg-git](https://github.com/nukata/cyg-git)

@eamodio Looking forward to your response. I’d really appreciate any update or insight on this. Thanks in advance!

**Comment by edemaine** [comment]
For what it's worth, I tried to make a more robust shim solution for using Cygwin Git in VS Code, inspired by [cyg-git](https://github.com/nukata/cyg-git). The result [Cygshim](https://github.com/edemaine/cygshim) should be easier to install (single prebuilt binary, then update PATH) and should handle edge cases better. Like cyg-git, it uses an `.exe` file not a `.bat` file, so side-steps this issue. Based on my preliminary testing, it supports Gitlens, including commit graph, branch view, inline blame, and file history. So you might give it a try, and if you have ideas for further improvements or extensions, let me know (on Cygshim repo).
